# -*- coding: utf-8 -*-
"""API cotizaciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Upr2yMtBu9Y_K42VGFDY4wWo9Vr1Z3o1
"""

import requests
import pandas as pd

historical_url = "https://api.exchangerate.host/timeseries"
base_currency = "USD"
target_currencies = "ARS,USD,UYU,COP,CLF,CLP,GTQ,PEN,CRC,HNL,NIO,MXN,DOP"
start_date = "2023-01-01"
end_date = "2023-12-31"

historical_params = {
    "start_date": start_date,
    "end_date": end_date,
    "base": base_currency,
    "symbols": target_currencies
}

response = requests.get(historical_url, params=historical_params)
data = response.json()

historical_rates = pd.DataFrame(data["rates"]).T

print(historical_rates)